### ISSUE TITLE
I could not activate the package yet

### ISSUE THREAD

**Issue by nomssi** [stockbal/abap-ui-toolbox#2]
![image](https://user-images.githubusercontent.com/18452507/113184137-1e1ca000-9255-11eb-87b5-699e386fdc40.png)

**Comment by stockbal** [comment]
Hi @nomssi,

I encountered this bug a while ago in another repository. 
There seems to be an issue in abapGit during TABL deserialization which was fixed in a newer version.

Please update your abapGit and perform the pull again.

Regards,
Ludwig

**Comment by nomssi** [comment]
I updated abapGit to the latest version. I had to pull more than once, but it worked, thanks.
